name: Dev Builds

on:
  push:
    branches: [ '**' ] # stop build tag commits
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  BUILD_TYPE: snapshot

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build_type: snapshot
      target_subproject: '26.1.2,26.2,26.3'
