name: PR Builds

on:
  pull_request:

permissions:
  contents: read
  packages: read

env:
  BUILD_TYPE: pr

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build_type: pr
      target_subproject: '26.1.2,26.2,26.3'
